### ISSUE TITLE
Request: Layer #

### ISSUE THREAD

**Issue by ekorolkov** [BillyBlaze/OctoPrint-FullScreen#11]
Nice plugin, thx!
Is it possible to add "Layer #/Total layers" info?

**Comment by BillyBlaze** [comment]
Hi @ekorolkov 

Thanks for requesting. Sadly it's not possible, I have quoted myself below as I did in #1 

"After diving into the source of OctoPrint I found out that there is no simple way of getting this information. As the information does not exist in the core of OctoPrint we need to implement our own analyzing and monitor tools for this information, this tools aren't easily made and require more code then the whole of this plugin.

I want to keep this plugin small and maintainable and therefor I will not implement or accept such code in this codebase. If there is easy access to this information (such as the temperatures) then I would be more then happy to implement this. That include if another plugin can provide this information.

Closing this request for now."

Please feel open to re-submit this if the information is accessible in OctoPrint or another plugin.
