### ISSUE TITLE
Feature Request: enable direct access with url

### ISSUE THREAD

**Issue by Patronics** [BillyBlaze/OctoPrint-FullScreen#12]
It would be useful to have an option to go straight to fullscreen mode with a link (for example how other tabs can be linked to by http://octoprint.ip/#control and http://octoprint.ip/#term (replacing octoprint.ip with the ip of the local octorprint instance, of course) or some other form like http://octoprint.ip/?fullscreen=true). 

This would be very useful for me, where I have a screen set up that automatically opens to octoprint (and some other useful functionality, each in their own iframes), but I manually have to double click to open the fullscreen view every time the page reloads (which is quite often while I'm working on the other functionality of the page). It would also solve problems for other users who are unable to double click for whatever reason (like in issue #7 ). It would also help make it better for the "Made for surveillance screen" use (similar to mine) suggested in a comment for issue #7 by @Idus.

**Comment by BillyBlaze** [comment]
Hi @Patronics,

Thanks for the suggestion, I will have a look at this in the upcoming release!
