### ISSUE TITLE
Feature Request: Status Bar Relocation

### ISSUE THREAD

**Issue by burghking** [BillyBlaze/OctoPrint-FullScreen#14]
Your plugin is a convenient and quick way to check status on a print. This is particularly helpful during the first layers of adhesion. For those like me who have a camera set low at bed height however the status bar obstructs the view of the bottom section of the video image even though it is dark transparent.  I suggest moving the status bar to the top of the screen where it is unlikely to impact visibility for the vast majority of users. Thanks for your consideration.

**Comment by BillyBlaze** [comment]
Sorry for the long delay and thank you for the feature request.

In the next release the bar will be replaced by vertically aligned information. This way we can show more information without a big bar on the bottom. Do you find this a good alternative for your situation?

![image](https://user-images.githubusercontent.com/445608/80410278-9c94f300-88ca-11ea-9159-390131598781.png)
