### ISSUE TITLE
Add a Chromecast button

### ISSUE THREAD

**Issue by mylife4aiurr** [BillyBlaze/OctoPrint-FullScreen#15]
If I'm watching my printer full screen on my phone or PC monitor I'd love the opportunity  to cast the video to my tv as well. I don't know how hard it is technically, would just love the option.

**Comment by BillyBlaze** [comment]
Sorry for the long delay and thanks for your request. Its not possible to cast the webcam image because its not really a video format. Most setups are just using the image tag.

However it would be possible ofcourse to cast the entire website to a Chromecast
