### ISSUE TITLE
Wrong direction for temperature arrows

### ISSUE THREAD

**Issue by phcoetzee** [BillyBlaze/OctoPrint-FullScreen#16]
Hi BillyBlaze,

Is it just me or do the arrows change direction the opposite way of how its suppose to change. What I mean by that is when my "Tool" temperature drops, the arrow is facing UP, and vise-versa. When my "Tool" temperature rise, the arrow is facing DOWN. Also when my "Bed" temperature drops, the arrow is facing UP, and vise-versa. When my "Bed" temperature rise, the arrow is facing DOWN.

Thanx
![fault](https://user-images.githubusercontent.com/38723167/39378891-f1b648a4-4a59-11e8-9c3f-cc2deeae0a13.jpg)

**Comment by BillyBlaze** [comment]
Hi @phcoetzee,

Sorry for the long delay. Over 2 years... I have no words except an apology.

The thought behind the arrow:

Bed: 60.4 (down arrow) 60

The current temperate is 60.4 and its target temperate is 60. Therefor the temperature needs to go down. This is what is visualized by the arrow. I have took this code from the NavBarTemp plugin made Jarek Szczepanski. Therefor I would like to keep this consistent with his plugin.
