### ISSUE TITLE
Feature request: Add exposed mjpg_streamer controls

### ISSUE THREAD

**Issue by opjose** [BillyBlaze/OctoPrint-FullScreen#18]
MJpg_streamer's installed example web page shows how to grab camera controls and display an interface based upon that to the user. This includes adjustments, lighting, camera pan and tilt controls, etc.

This is accessible if you run the startup.sh script in the mjpg_streamer folder.

Currently there is no way to have those controls co-exist with octoprint.
Could you add those controls? That would be a wonderful addition for most people.

**Comment by BillyBlaze** [comment]
Sorry for the long delay. I wont add any functionality that is not really related to the fullscreen plugin. I am keeping this simple so its easier to maintain. I however will facilitate any other OctoPrint plugins that support this and if it doesn't work with this plugin then I would love to hear it.
