### ISSUE TITLE
Z-Height

### ISSUE THREAD

**Issue by Hellfalk** [BillyBlaze/OctoPrint-FullScreen#20]
Hi! Awesome plugin. Only addition I can think of is to ba able to see z-height. Would be sweet.

**Comment by guestisp** [comment]
+1. I was trying to open this exact issue but i've seen that you already did this.

Z-Height and Z layer, in example: Layer: 1 (0.3mm)

**Comment by BillyBlaze** [comment]
Thanks for reporting. Layer height is now reported if you have the plugin DisplayLayerProgress installed.
