### ISSUE TITLE
Fullscreen information not displaying

### ISSUE THREAD

**Issue by AbuMaia** [BillyBlaze/OctoPrint-FullScreen#21]
OctoPrint 1.3.12 running on OctoPi 0.15.1 

The information shown at the bottom of the screen when the camera is in fullscreen mode (temperature, elapsed time, total time, etc) no longer appears.

![Screenshot from 2020-01-24 13-21-59](https://user-images.githubusercontent.com/9308040/73101511-11602780-3ead-11ea-86dd-ddb0f048114f.png)

**Comment by AbuMaia** [comment]
Turns out this was being caused by the Dashboard plugin. Disabling Dashboard causes the temperature and print times to display again.

**Comment by BillyBlaze** [comment]
Thanks for reporting. I will address this issue in the next release.

**Comment by AbuMaia** [comment]
Oh wow, this plugin lives.
I was about to report it as abandoned.
