### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by bbrendon** [BillyBlaze/OctoPrint-FullScreen#22]
I can't get this to install ...I think it's because it doesn't support python3. Feature request?

**Comment by ChaosBlades** [comment]
Yes it does need Python 3 support as Python 2 is EOL and won't get any more security updates but it works fine on the latest version of OctoPi and OctoPrint.

Will it get an update is another question as it seems like the last update was in 2017.

**Comment by gvmturl** [comment]
add on __init__.py
``__plugin_pythoncompat__ = ">=2.7,<4"``

like

__plugin_name__ = "Fullscreen Plugin"
__plugin_pythoncompat__ = ">=2.7,<4"

**Comment by BillyBlaze** [comment]
Thanks for reporting. I will fix this in the next release.
