### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by Brebinator** [BillyBlaze/OctoPrint-FullScreen#26]
Ocotoprint will no longer support previous versions of python in the near future, it would be awesome if this plugin could get updated to be compatible with python 3.6.

**Comment by BillyBlaze** [comment]
Hi @Brebinator,

Python 3.6 is already supported in 0.0.5. See https://github.com/BillyBlaze/OctoPrint-FullScreen/blob/master/octoprint_fullscreen/__init__.py#L41

The only thing is that I still need to mark this in the Plugins repository.
