### ISSUE TITLE
Aspec ratio

### ISSUE THREAD

**Issue by R5fan** [BillyBlaze/OctoPrint-FullScreen#3]
Love the plugin, but my camera gives a 4:3 video, while my screen is a 21:9 ultrawide. When I go full screen, it chops off the top and bottom and zooms in on the center part. I would rather have black bars on the side if possible.

**Comment by barrettdent** [comment]
I agree with R5fan. A maintain aspect ratio option that pillar boxes the image to avoid top/bottom cutting would be a very useful addition.

**Comment by BillyBlaze** [comment]
Thanks for reporting! This is now fixed in the v0.0.2 release.
