### ISSUE TITLE
HLS support

### ISSUE THREAD

**Issue by claytono** [BillyBlaze/OctoPrint-FullScreen#31]
Octoprint 1.5.0rc1 added support for HLS streaming instead of MJPEG.  It looks like as a result some of the element names have changed and the full screen plugin does not work with HLS streams.

Just thought you might want to know.  Thanks for the plugin!

**Comment by mkocus** [comment]
@claytono I've got the same issue after switching to HLS. How did you managed to resolve that issue?

**Comment by claytono** [comment]
I never resolved it, I just closed it because I was tired of having it in my issues list.
