### ISSUE TITLE
Plugin stopped working after the last OctoPrint update

### ISSUE THREAD

**Issue by Snakn1** [BillyBlaze/OctoPrint-FullScreen#32]
After I updated the OctoPrint
 to the newest version last night the dbl click to full screen stopped working. Please look in to it. i have already tried to re install it. 
[octoprint.zip](https://github.com/BillyBlaze/OctoPrint-FullScreen/files/5526920/octoprint.zip)

**Comment by k7beb** [comment]
Same here - does not work on 1.5.0rc1 of OctoPrint.

**Comment by ChrisHeerschap** [comment]
Also seeing this issue with 1.5.0rc1 - probably worth mentioning in the title that it's not working with an Octoprint RC, not the last _release_ update. Was working fine with that.

Mentioned in the 1.5.0rc1 feedback issue: https://github.com/OctoPrint/OctoPrint/issues/3802

**Comment by lgraak** [comment]
> 
> 
> Also seeing this issue with 1.5.0rc1 - probably worth mentioning in the title that it's not working with an Octoprint RC, not the last _release_ update. (I think that was 1.4.3?) This plugin was working fine with that.
> 
> Mentioned in the 1.5.0rc1 feedback issue: [OctoPrint/OctoPrint#3802](https://github.com/OctoPrint/OctoPrint/issues/3802)

As of today, it's still not working with 1.5.0RC3. Didn't think it would fix it, but figured I'd update.

**Comment by AndKe** [comment]
same here, 1.5.0 RC3 is not working..

**Comment by BillyBlaze** [comment]
Thanks for reporting.

This is fixed in 0.0.6

**Comment by Snakn1** [comment]
thank you

**Comment by ChrisHeerschap** [comment]
Confirmed all is right with the world again. _(I mean, aside from all the other crazy s!!! going on.)_

Thanks for the quick fix! Love this plugin and found myself continually confused each time I double-clicked on the previous version. 😄 I use it often enough that it's second nature.
