### ISSUE TITLE
External request to webcam url with credentials no longer works

### ISSUE THREAD

**Issue by totalitarian** [BillyBlaze/OctoPrint-FullScreen#6]
My webcam url takes the form of

http://username:password@webcamhost.com:7777/video

The webcam is actually an android phone running ipcam software. Since the latest update to chrome, embedding credentials in a url has been dropped. The result is I get the following message in the UI

If I load the url directly in a new tab it works fine. How best to connect to a webcam that requires a username/password?

Another reference here http://support.actiontiles.com/topics/1292-url-login-credentials-for-ip-webcam-not-working-upon-load-in-media-tile/
![capture 1](https://user-images.githubusercontent.com/2385696/27681613-c1c3aa96-5cb7-11e7-8520-26bfc62c409c.PNG)

**Comment by BillyBlaze** [comment]
Hi,

Thanks for reporting. But I am afraid you're in the wrong place to report it.
This plugin doesn't extend or add the stream logic, it only puts the image into fullscreen mode.

The best place to report this is in the issue tracker of [OctoPrint](https://github.com/foosel/OctoPrint/issues)
