### ISSUE TITLE
request: Button for Fullscreen / disable keyboard

### ISSUE THREAD

**Issue by COOLover** [BillyBlaze/OctoPrint-FullScreen#7]
Hello,
1. sorry for my bad english ;-) i won't use translators
2. greate Plugin for OctoPrint! i like it.
3. here two request:

3.1
I look with my smartphone on my OctoPrint, and can't make a double touch to Fullscreen. So is it posible to add a Fullscreen Button at the main Image?

3.2
wenn i'm at the compute, so i work more with my keyboard as with the mouse, so i would like to disable the keyboard. is it posible to disable it?

Best regard form Germany!

Marco

**Comment by BillyBlaze** [comment]
Hi @COOLover,

Sorry for the delayed response.

1. Even on mobile you should be able to double tap? Atleast I know this works on my touchscreen with TouchUI and on my android phone.

2. Disabling the functionality of your keyboard is built within OctoPrint. You can disable it in your settings.

**Comment by ChiefPoints** [comment]
I can confirm that the double-tap doesn't work on iOS, tried in just about every mainstream mobile browser for iOS 11. Something like a button to go to full screen would be wonderful, as I really miss this great functionality on my phone. 
Great idea with the plugin, thanks for sharing!

Chief

**Comment by BillyBlaze** [comment]
Hi @ChiefPoints,

Thanks for the information! Could you clarify something for me?
Do you use this on your mobile in combination with TouchUI?
If not; can you install TouchUI, try it on your phone, and see if double tab works on there?

**Comment by Idus** [comment]
Hello,

Funny you contacted me - I was about to send YOU a mail and suggest your
next project. ;)

But first to your question.

I am three days into 3D-printing and just bought a used printer and
"smartbox-setup" (OctoPie etc.). Yep, I use the TouchUI - but you need to
define where I see the double tab works.

About my suggestions.

What about doing a plugin that is "made for a survaillance screen". I would
love your Fullscreen + a small corner with a job progross of GCode Viewer
and parhaps temperature graphs. I have a seperate screen in my room on a
IntelNUC that now displays about 1/2 screen with your Fullscreen - then
another browser window (1/4) showing the GCode Viewer and the last 1/4
showing temperature. Anyway - it was just a thought. :)

Cheers,

/Fred

**Comment by ChiefPoints** [comment]
I don't use TouchUI, but I'll install it later and check it out. I'll get back to you when I do, thanks for the reply!

**Comment by ChiefPoints** [comment]
Just tested it out and still doesn't work with TouchUI. Looks like iOS intercepts the double click for it's page zoom function. Doesn't look like there's a setting to change that behavior either. Looks like a button to change mode might be the next best thing for iOS users.

**Comment by Idus** [comment]
Juuust tried it out and it works on Android - but just with *one tap* once
inside the webcam menu

[image: Inline images 2]

also, by tapping the "maximize" button in the lower right - I get to a
slightly larger "maximized" version:

[image: Inline images 1]

...and I can minimize back to previous. :)

Hope that helps your development?

Cheers!

/Fred

**Comment by BillyBlaze** [comment]
Thanks all for the report. I was able to reproduce the problem and the double-tap functionality will be restored in the upcoming release. 

Releasing will be now.

**Comment by BillyBlaze** [comment]
And it's released! Thanks for reporting!

**Comment by ChiefPoints** [comment]
outstanding, thanks!

**Comment by ChiefPoints** [comment]
tested and works great, thanks again!
